/// Build script — injects the notary address at compile time.
///
/// Reads NOTARY_ADDRESS from the environment (set by the web app build script)
/// and generates `notary_account.rs` in OUT_DIR, which src/lib.rs includes.
///
/// Default (no env var): uses the Ripple genesis account for local testing.

use std::io::Write;

const DEFAULT_NOTARY: &str = "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh";

fn main() {
    let addr = std::env::var("NOTARY_ADDRESS").unwrap_or_else(|_| DEFAULT_NOTARY.to_string());
    let addr = addr.trim();

    // Validate: XRPL r-addresses are 25–34 chars and start with 'r'
    assert!(
        addr.starts_with('r') && (25..=34).contains(&addr.len()),
        "NOTARY_ADDRESS does not look like a valid XRPL address: {addr}"
    );

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set by Cargo");
    let dest = format!("{out_dir}/notary_account.rs");

    let mut f = std::fs::File::create(&dest).expect("cannot write notary_account.rs");
    writeln!(f, "// Auto-generated by build.rs — do not edit.").unwrap();
    writeln!(f, "// Notary: {addr}").unwrap();
    writeln!(f, "const NOTARY_ACCOUNT: [u8; 20] = r_address!(\"{addr}\");").unwrap();

    // Re-run only when this env var changes, not on every build
    println!("cargo:rerun-if-env-changed=NOTARY_ADDRESS");
    println!("cargo:rerun-if-changed=build.rs");
}
