/// Build script — injects the notary address and verdict at compile time.
///
/// Reads NOTARY_ADDRESS and WASM_VERDICT from the environment (set by the
/// web app build script) and generates two files in OUT_DIR:
///   - notary_account.rs  — the authorised notary as a 20-byte account ID
///   - verdict.rs         — IS_PENALTY: bool (false = refund, true = penalty)
///
/// Default (no env vars):
///   NOTARY_ADDRESS → Ripple genesis account (for local testing)
///   WASM_VERDICT   → "refund"

use std::io::Write;

const DEFAULT_NOTARY: &str = "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh";

fn main() {
    // ── notary address ────────────────────────────────────────────────────────
    let addr = std::env::var("NOTARY_ADDRESS").unwrap_or_else(|_| DEFAULT_NOTARY.to_string());
    let addr = addr.trim();

    assert!(
        addr.starts_with('r') && (25..=34).contains(&addr.len()),
        "NOTARY_ADDRESS does not look like a valid XRPL address: {addr}"
    );

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set by Cargo");

    let account_path = format!("{out_dir}/notary_account.rs");
    let mut f = std::fs::File::create(&account_path).expect("cannot write notary_account.rs");
    writeln!(f, "// Auto-generated by build.rs — do not edit.").unwrap();
    writeln!(f, "// Notary: {addr}").unwrap();
    writeln!(f, "const NOTARY_ACCOUNT: [u8; 20] = r_address!(\"{addr}\");").unwrap();

    // ── verdict ───────────────────────────────────────────────────────────────
    // "penalty" → funds go to landlord on EscrowFinish (condition is Poor)
    // "refund"  → funds go to tenant on EscrowFinish (condition is acceptable)
    let verdict_raw = std::env::var("WASM_VERDICT").unwrap_or_else(|_| "refund".to_string());
    let verdict_raw = verdict_raw.trim();

    let is_penalty = match verdict_raw {
        "penalty" => true,
        "refund" => false,
        other => panic!("WASM_VERDICT must be 'refund' or 'penalty', got: {other}"),
    };

    let verdict_path = format!("{out_dir}/verdict.rs");
    let mut v = std::fs::File::create(&verdict_path).expect("cannot write verdict.rs");
    writeln!(v, "// Auto-generated by build.rs — do not edit.").unwrap();
    writeln!(v, "// Verdict: {verdict_raw}").unwrap();
    writeln!(v, "const IS_PENALTY: bool = {is_penalty};").unwrap();

    println!("cargo:rerun-if-env-changed=NOTARY_ADDRESS");
    println!("cargo:rerun-if-env-changed=WASM_VERDICT");
    println!("cargo:rerun-if-changed=build.rs");
}
